const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const A=require('../dist/vendor/astronomy.browser.min.js'),c=vm.createContext({Astronomy:A,Intl,Date,console});
for(const file of ['mooncalc.js','core.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),c);
const C=c.CalendarCore,L=c.LunarCalc,loc={...C.defaults};
const time=(date)=>date?.toISOString().slice(11,19);
test('three calendars round-trip Arabic input and Gregorian leap day',()=>{const date=C.calendarDate('٢٠٢٤','٢','٢٩');assert.equal(date.toISOString().slice(0,10),'2024-02-29');for(const cal of ['gregory','persian','islamic-umalqura']){const p=C.parts(date,cal);assert.equal(+C.calendarDate(p.year,p.month,p.day,cal),+date);}assert.throws(()=>C.calendarDate(2023,2,29));assert.throws(()=>C.calendarDate(2026,13,1));});
test('major living calendars round-trip through the shared converter',()=>{const date=new Date('2026-09-07T12:00:00Z');for(const cal of ['hebrew','indian','ethiopic','coptic','buddhist']){const p=C.parts(date,cal);assert(Number.isInteger(p.month),cal);assert.equal(+C.calendarDate(p.year,p.month,p.day,cal),+date,cal);}});
test('clock switches between 24-hour and 12-hour display',()=>{const date=new Date('2026-09-07T13:05:00Z'),utc={...loc,zone:'UTC'};C.setHourCycle('h23');assert.equal(C.hourCycle,'h23');assert.doesNotMatch(C.clock(date,false,utc),/[صم]/);C.setHourCycle('h12');assert.equal(C.hourCycle,'h12');assert.match(C.clock(date,false,utc),/[صم]/);C.setHourCycle('h23');});
test('Umm al-Qura prayers are conservatively rounded to the next whole minute',()=>{const p=C.prayers('2026-09-07',loc);const fixture={fajr:'01:49:00',sunrise:'03:06:00',dhuhr:'09:19:00',asr:'12:44:00',maghrib:'15:32:00',isha:'17:02:00'};for(const [key,expected]of Object.entries(fixture))assert.equal(time(p[key]),expected,key);for(const key of Object.keys(fixture))assert.equal(+p[key]%60000,0,key);});
test('Dammam timetable matches the displayed whole-minute fixture',()=>{const dammam={...loc,lat:26.4207,lon:50.0888,zone:'Asia/Riyadh'},p=C.prayers('2026-09-07',dammam),fixture={fajr:'01:02:00',sunrise:'02:22:00',dhuhr:'08:38:00',asr:'12:08:00',maghrib:'14:54:00',isha:'16:24:00'};for(const [key,expected]of Object.entries(fixture))assert.equal(time(p[key]),expected,key);});
test('prayer-page solar timeline follows the calculated daylight arc',()=>{const p=C.prayers('2026-09-06',loc),chart=C.solarTimeline(p.dhuhr,loc,72);assert.equal(chart.points.length,73);assert.equal(chart.daylight,true);assert(Math.abs(chart.progress-.5)<.03);assert(chart.sun.altitude>65);assert(chart.maxAltitude>=chart.sun.altitude-.1);assert(Math.abs(chart.points[0].altitude)<1);assert(Math.abs(chart.points.at(-1).altitude)<1);const night=C.solarTimeline(new Date(+p.fajr-3600000),loc);assert.equal(night.daylight,false);});
test('Isha follows Ramadan night and normal 90 minute offset',()=>{for(const [iso,minutes]of [['2026-02-25',120],['2026-09-06',90]]){const p=C.prayers(iso,loc);assert.equal((p.isha-p.maghrib)/60000,minutes);}});
test('Bahrain resolves automatically to the Zubarah and Bahrain calendar',()=>{
 const manama={...loc,name:'المنامة',lat:26.2235,lon:50.5876,zone:'Asia/Bahrain',prayerMethod:'auto'},p=C.prayers('2026-09-10',manama);
 assert.equal(C.resolvedPrayerMethod(manama),'zubarah');assert.equal(p.method,'zubarah');assert.equal(p.methodName,'روزنامة الزبارة والبحرين');assert.equal(p.fajrAngle,18);assert.equal(p.ishaRule,'angle18');
});
test('Zubarah calendar is a national timetable and Isha follows astronomical twilight',()=>{
 const manama={...loc,lat:26.2235,lon:50.5876,zone:'Asia/Bahrain',prayerMethod:'auto'},riffa={...manama,lat:26.13,lon:50.555},summer=C.prayers('2026-06-21',manama),winter=C.prayers('2026-12-21',manama);
 for(const key of ['fajr','sunrise','dhuhr','asr','maghrib','isha'])assert.equal(+C.prayers('2026-09-10',manama)[key],+C.prayers('2026-09-10',riffa)[key],key);
 const summerGap=(summer.isha-summer.maghrib)/60000,winterGap=(winter.isha-winter.maghrib)/60000;assert(summerGap>=85&&summerGap<=95);assert(winterGap>=75&&winterGap<=85);assert(summerGap>winterGap);
});
test('Prayer method can be selected explicitly without changing other locations',()=>{
 const riyadh={...loc,name:'الرياض',lat:24.7136,lon:46.6753,prayerMethod:'auto'},forced={...riyadh,prayerMethod:'zubarah'};
 assert.equal(C.resolvedPrayerMethod(riyadh),'ummalqura');assert.equal(C.prayers('2026-09-10',riyadh).ishaRule,'offset90');assert.equal(C.prayers('2026-09-10',forced).ishaRule,'angle18');
});
test('polar day and polar night do not invent shadow or twilight events',()=>{const l={...loc,lat:69.6492,lon:18.9553,zone:'Europe/Oslo'};const summer=C.prayers('2026-06-21',l),winter=C.prayers('2026-12-21',l);for(const key of ['fajr','sunrise','maghrib','isha'])assert.equal(summer[key],null,key);assert.equal(winter.asr,null);});
test('local day starts survive skipped midnight and 23/25 hour DST days',()=>{for(const [iso,zone,hours]of [['2026-09-06','America/Santiago',23],['2026-03-08','America/New_York',23],['2026-11-01','America/New_York',25]]){const b=L.dayBounds(iso,zone);assert.equal((b.end-b.start)/3600000,hours);assert.equal(L.dateISO(b.start,zone),iso);}assert.doesNotThrow(()=>C.prayers('2026-09-06',{...loc,lat:-33.4489,lon:-70.6693,zone:'America/Santiago'}));});
test('global eclipse catalog includes hybrid 2031 and correct Saudi local date',()=>{const list=C.eclipses(2031,loc),e=list.find(e=>e.type==='solar'&&new Date(e.peakAt).getUTCMonth()===10);assert(e.title.includes('هجين'));assert.equal(L.dateISO(new Date(e.peakAt),loc.zone),'2031-11-15');assert.equal(e.visible,false);});
test('Mecca lunar eclipse visible early even when peak is below horizon',()=>{const e=C.eclipses(2026,loc).find(e=>e.type==='lunar'&&new Date(e.peakAt).getUTCMonth()===7);assert.equal(e.visible,true);assert(L.horizontal('Moon',new Date(e.peakAt),loc).altitude<0);assert(e.intervals[0][1]<e.peakAt);assert(Math.abs(e.intervals[0][1]-Date.parse('2026-08-28T03:03:26Z'))<60000);});
test('Madrid solar visibility window stops at sunset',()=>{const madrid={...loc,lat:40.4168,lon:-3.7038,zone:'Europe/Madrid'},e=C.eclipses(2026,madrid).find(e=>e.type==='solar'&&new Date(e.peakAt).getUTCMonth()===7);assert(e.visible);assert(e.visibleEndAt<e.endAt);assert(Math.abs(e.visibleEndAt-Date.parse('2026-08-12T19:16:23Z'))<60000);});
test('global solar eclipses do not fabricate local contacts for Mecca',()=>{const e=C.eclipses(2026,loc).find(e=>e.type==='solar'&&e.kind==='annular');assert.equal(e.local,false);assert.equal(e.visible,false);assert.equal(e.contactStartAt,null);assert.equal(e.contactEndAt,null);assert.equal(e.start,'لا تماس محلي');});
test('Mecca 2027 total solar eclipse has ordered local contacts and full obscuration',()=>{const e=C.eclipses(2027,loc).find(e=>e.type==='solar'&&e.local);assert.equal(e.localKind,'total');assert.equal(e.visible,true);assert.equal(e.obscuration,1);assert(e.contactStartAt<e.centralStartAt);assert(e.centralStartAt<e.peakAt);assert(e.peakAt<e.centralEndAt);assert(e.centralEndAt<e.contactEndAt);});
test('total lunar eclipse exposes penumbral, partial and total contacts in order',()=>{const e=C.eclipses(2026,loc).find(e=>e.type==='lunar'&&e.kind==='total');assert(e.penumbralStartAt<e.partialStartAt);assert(e.partialStartAt<e.totalStartAt);assert(e.totalStartAt<e.peakAt);assert(e.peakAt<e.totalEndAt);assert(e.totalEndAt<e.partialEndAt);assert(e.partialEndAt<e.penumbralEndAt);});
test('all seasonal runs agree with their season index over 68 annual positions',()=>{const source=fs.readFileSync('dist/app.js','utf8'),start=source.indexOf('const SYNC_TROPICAL_YEAR='),end=source.indexOf('function renderSyncSeasonSchedule()');vm.runInContext('const arDigits=String;'+source.slice(start,end),c);const runs=vm.runInContext('syncSeasonRuns()',c);assert.equal(runs.at(-1).end,67);assert.equal(runs.reduce((n,r)=>n+r.count,0),68);assert.equal(vm.runInContext('syncSeasonAt(31).label',c),'الشتاء');assert(Math.abs(vm.runInContext('syncSeasonAt(31).longitude',c)-358.00694)<.001);});
