const fs=require('node:fs'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
function load(){const values=new Map(),context=vm.createContext({console,Blob,crypto:{randomUUID:()=>"test-sound-id"},localStorage:{getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)}});vm.runInContext(fs.readFileSync('dist/prayer-sounds.js','utf8'),context);return {sounds:context.PrayerSounds,values};}
test('two named adhans are built in while the first remains the default for every alarm',()=>{const {sounds}=load(),assignments=sounds.defaults(),keys=['fajr','dhuhr','asr','maghrib','isha','rawatib','eclipse-lunar','eclipse-solar','jumuah','eid','istisqa','iqamah'],source=fs.readFileSync('dist/prayer-sounds.js','utf8');assert.deepEqual(Object.keys(assignments),keys);for(const key of keys)assert.equal(assignments[key],'builtin:official-adhan');assert.equal(JSON.stringify(sounds.BUILTIN_SOUNDS.map(({key,name})=>({key,name}))),JSON.stringify([{key:'official-adhan',name:'الأذان الأول — الشيخ عبدالعزيز الزري'},{key:'adhan-mansour-altamimi',name:'الأذان الثاني — الشيخ منصور التميمي'}]));assert(source.includes("./audio/official-adhan.mp3"));assert(source.includes("./audio/adhan-sheikh-mansour-altamimi.m4a"));assert(fs.existsSync('dist/audio/official-adhan.mp3'));assert(fs.existsSync('dist/audio/adhan-sheikh-mansour-altamimi.m4a'));});
test('sound assignments preserve personal recordings and the second adhan while rejecting removed built-in choices',()=>{const {sounds}=load(),assignments=sounds.normalizeAssignments({fajr:'custom:recording-123',dhuhr:'builtin:adhan-makkah',rawatib:'builtin:adhan-madinah',eid:'builtin:adhan-aqsa',istisqa:'builtin:adhan-mansour-altamimi',iqamah:'builtin:iqamah-bell'});assert.equal(assignments.fajr,'custom:recording-123');assert.equal(assignments.istisqa,'builtin:adhan-mansour-altamimi');for(const key of ['dhuhr','rawatib','eid','iqamah'])assert.equal(assignments[key],'builtin:official-adhan');assert.equal(sounds.BUILTIN_SOUNDS.length,2);});
test('sound assignments are saved locally',()=>{const {sounds,values}=load(),assignments=sounds.defaults();assignments.maghrib='custom:uploaded-456';assert.equal(sounds.saveAssignments(assignments),true);assert.match(values.get('calendar.prayerSoundAssignments'),/custom:uploaded-456/);});
test('the alarm page exposes upload, microphone recording, and the sounds tab offline',()=>{
 const html=fs.readFileSync('dist/index.html','utf8'),sw=fs.readFileSync('dist/sw.js','utf8'),manifest=fs.readFileSync('android-app/app/src/main/AndroidManifest.xml','utf8');
 assert(html.includes('data-worship-tab="sounds"'));assert(html.includes('id="soundFile" type="file" accept="audio/*"'));assert(html.includes('id="recordSound"'));assert(html.includes('الشيخ عبدالعزيز الزري'));assert(html.includes('الشيخ منصور التميمي'));assert(html.indexOf('./prayer-sounds.js')<html.indexOf('./live-app.js'));
 assert(html.includes('option value="rawatib"'));assert(html.includes('option value="eclipse-lunar"'));assert(html.includes('option value="eclipse-solar"'));assert(html.includes('option value="jumuah"'));assert(html.includes('option value="eid"'));assert(html.includes('option value="istisqa"'));assert(html.includes('option value="iqamah"'));
 assert(html.includes('id="jumuahCustomTime" type="time"'));assert(html.includes('id="eidCustomTime" type="time"'));assert(html.includes('id="istisqaCustomAt" type="datetime-local"'));assert(html.includes('id="iqamahFajr" type="number"'));assert(html.includes('id="iqamahJumuah" type="number"'));
 assert(sw.includes('"./prayer-sounds.js"'));assert(manifest.includes('android.permission.RECORD_AUDIO'));assert(manifest.includes('android:name=".AlarmSoundService"'));assert(fs.readFileSync('android-app/app/src/main/java/com/mohammadalmuhanna/universalcalendar/MainActivity.java','utf8').includes('previewAlarmSound'));assert(fs.readFileSync('dist/prayer-sounds.js','utf8').includes('AndroidCalendar?.previewAlarmSound'));
});
